#define ERROR_GENERIC			 -1
#define ERROR_NO_DISK			 -2
#define ERROR_INVALID_ID		 -3
#define ERROR_READ_ONLY			 -4
#define ERROR_READ				 -5
#define ERROR_WRITE				 -6
#define ERROR_TOO_MANY_OPEN	     -10
#define ERROR_NO_DRIVER			 -11
#define ERROR_NOT_MOUNTED		 -12
#define ERROR_NOT_READY		     -13
#define ERROR_WOULD_BLOCK	     -14
#define ERROR_UNSUPPORTED_OP	 -15
#define ERROR_EXCLUSIVE_LOCK	 -16
#define ERROR_END_OF_STREAM	     -17
#define ERROR_EXCLUSIVE_OP		 -18
#define ERROR_UNKNOWN_FS		 -50
